version: 2.1

orbs:
  snyk: snyk/snyk@1.1.1
  win: circleci/windows@2.4
  prodsec: snyk/prodsec-orb@1

defaults: &defaults
  working_directory: ~/snyk-iac-parsers

commands:
  build:
    description: Build Golang library
    steps:
      - run:
          name: Build
          command: go build ./...
  test:
    description: Runs the regression tests
    steps:
      - run:
          name: Run Golang tests
          command: go test ./...

jobs:
  lint_and_format:
    <<: *defaults
    description: Lint & formatting
    docker:
      - image: golangci/golangci-lint:v1.42
    steps:
      - checkout
      - attach_workspace:
          at: ~/snyk-iac-parsers
      # Logs the version in our build logs, for posterity
      - run: go version
      - run:
          name: "Ensure go.mod is tidy"
          command: |
            go mod tidy
            git diff --exit-code go.mod go.sum
      - run:
          name: "Run golangci-lint"
          command: golangci-lint run -v --timeout 10m
      - run:
          name: "Run gofmt"
          command: "! gofmt -d -e . | read"
  regression-test-linux:
    <<: *defaults
    docker:
      - image: cimg/go:1.18.4
    steps:
      - checkout
      - build
      - test
  regression-test-windows:
    <<: *defaults
    executor:
      name: win/default
      size: medium
    steps:
      - checkout
      - build
      - test
  security-scans:
    resource_class: small
    docker:
      - image: cimg/go:1.18.4
    steps:
      - checkout
      - prodsec/security_scans:
          mode: auto

workflows:
  version: 2
  test:
    jobs:
      - prodsec/secrets-scan:
          name: Scan Repository for Secrets
          context:
            - snyk-bot-slack
          channel: group-infrastructure-as-code-alerts
      - security-scans:
          name: Security Scans
          context:
            - analysis-iac
      - lint_and_format:
          name: Lint & formatting
      - regression-test-linux:
          name: Regression Test (Linux)
      - regression-test-windows:
          name: Regression Test (Windows)
